### PR TITLE
Updated readme with additional installation instructions

### PR DESCRIPTION
**Pull request by apetkau**
Fix for #51 

The conda package is now created. This PR adds the instructions to the README.md file for installing using conda.

### CODE REVIEW

**Review by emarinier — APPROVED** [review]
Looks good to me. My only thought is whether or not you want to mention in the README the possibility of using mamba if conda doesn't work. I don't think it's necessary though.

**Comment by apetkau** [comment]
> Looks good to me. My only thought is whether or not you want to mention in the README the possibility of using mamba if conda doesn't work. I don't think it's necessary though.

Thanks. I agree. I've added instructions for mamba in 0001688b0e94a90bd6fa364292d32da99627923a

**Comment by emarinier** [comment]
Looks good to me!

**Comment by apetkau** [comment]
Awesome. I will merge it in

**Pull request merged**
